# Generated by Django 3.2.4 on 2021-06-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
